searchandrescue/config/routes.rb
Rails.application.routes.draw do
  root 'places#index'
  
  resources :places
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

searchandrescue/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

searchandrescue/app/models/place.rb
class Place < ApplicationRecord
  mount_uploaders :images, ImageUploader
  serialize :images, JSON # If you use SQLite, add this line.
  
  attr_accessor :name, :latitude, :longitude
  
  # Modified from Paul Faugeras' Computer-Vision-Emergency-Response-Toolkit
  def find_fov(s)
    if(s.class == String)
      case s
        when "FC220"
          return 78.8
        when "FC1102"
          return 81.9
        when "FC200"
          return 85
        when "FC2103"
          return 85
        when "FC300"
          return 94
        when "FC7203"
          return 83
        when "FC330"
          return 94
        when "FC6310S"
          return 84
        when "FC6310"
          return 84
        when "ZENMUSE Z30"
          return 63.7
      end
    else
      return nil
    end
    
  end
  
  def find_sensor_height(s)
    if(s.class == String)
      case s
        when "FC6310S"
          return 8.80
        when "ZENMUSE Z30"
          return 3.556
      end
    else
      return nil
    end

  end
  
  def find_sensor_width(s)
    if(s.class == String)
      case s
        when "FC6310S"
          return 13.20
        when "ZENMUSE Z30"
          return 4.826
      end
    else
      return nil
    end
  end
  
  def get_direction(s)
    if(s > 180 || s < -180)
      return nil
    end
      
    if(s >= -22.5 && s <= 22.5)
      return "E"
    elsif(s > 22.5 && s <= 67.5)
      return "SE"
    elsif(s > 67.5 && s <= 112.5)
      return "S"
    elsif(s > 112.5 && s <= 158.5)
      return "SW"
    elsif(s < -22.5 && s >= -67.5)
      return "NE"
    elsif(s < -67.5 && s >= -112.5)
      return "N"
    elsif(s < -112.5 && s >= -158.5)
      return "NW"
    else
      return "W"
    end
  end
  
end

searchandrescue/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

searchandrescue/app/controllers/places_controller.rb
require 'exifr/jpeg'

class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
    @placeAry = []
    @places.each do |f|
      if(!f.images.empty?)
        f.images.each do |j|
          if(EXIFR::JPEG.new("public" + j.url).date_time != nil && EXIFR::JPEG.new("public" + j.url).gps != nil)
            @tempAry = [j.url, EXIFR::JPEG.new("public" + j.url).gps.latitude, EXIFR::JPEG.new("public" + j.url).gps.longitude, EXIFR::JPEG.new("public" + j.url).date_time.to_formatted_s(:long), Exiftool.new("public" + j.url).to_hash[:gimbal_yaw_degree], Exiftool.new("public" + j.url).to_hash[:gimbal_pitch_degree], Exiftool.new("public" + j.url).to_hash[:gimbal_roll_degree], Exiftool.new("public" + j.url).to_hash[:absolute_altitude], f.find_fov(EXIFR::JPEG.new("public" + j.url).model), f.find_sensor_height(EXIFR::JPEG.new("public" + j.url).model), f.find_sensor_width(EXIFR::JPEG.new("public" + j.url).model), Exiftool.new("public" + j.url).to_hash[:focal_length], f.get_direction(Exiftool.new("public" + j.url).to_hash[:gimbal_yaw_degree])]
            @placeAry.push(@tempAry)
          end
        end
      end
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    
    respond_to do |format|
      if @place.save
        format.html
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
    redirect_to places_path
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude, images: [])
    end
end

searchandrescue/app/helpers/application_helper.rb
module ApplicationHelper
end

searchandrescue/app/helpers/places_helper.rb
module PlacesHelper
end

searchandrescue/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Searchandrescue</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

searchandrescue/app/views/places/_form.html.erb
<%= form_for(place) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

searchandrescue/app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

searchandrescue/app/views/places/index.html.erb
<p id="notice"><%= notice %></p>
<head>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
  <script src="/leaflet.polylineDecorator.js"></script>
  
  <style>
    #map {
      margin: 0;
      position: absolute; 
      top: 50%; 
      left: 50%;
      transform: translate(-50%, -50%);
      width:1050px; 
      height:860px;
    }
    
    /* The Modal (background) */
    .Modal {
      display: none; /* Hidden by default */
      position: fixed; /* Stay in place */
      z-index: 1; /* Sit on top */
      padding-top: 100px; /* Location of the box */
      left: 0;
      top: 0;
      width: 100%; /* Full width */
      height: 100%; /* Full height */
      overflow: auto; /* Enable scroll if needed */
      background-color: rgb(0,0,0); /* Fallback color */
      background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
    }
    
    /* Modal Content (image) */
    .modal-content {
      margin: auto;
      display: block;
      width: 80%;
      max-width: 700px;
    }

    /* Caption of Modal Image */
    .caption {
      margin: auto;
      display: block;
      width: 80%;
      max-width: 700px;
      text-align: center;
      color: #ccc;
      padding: 10px 0;
      height: 150px;
    }

    /* Add Animation */
    .modal-content, #caption {  
      -webkit-animation-name: zoom;
      -webkit-animation-duration: 0.6s;
      animation-name: zoom;
      animation-duration: 0.6s;
    }

    @-webkit-keyframes zoom {
      from {-webkit-transform:scale(0)} 
      to {-webkit-transform:scale(1)}
    }

    @keyframes zoom {
      from {transform:scale(0)} 
      to {transform:scale(1)}
    }

    /* The Close Button */
    .close {
      position: absolute;
      top: 15px;
      right: 35px;
      color: #f1f1f1;
      font-size: 40px;
      font-weight: bold;
      transition: 0.3s;
    }

    .close:hover,
    .close:focus {
      color: #bbb;
      text-decoration: none;
      cursor: pointer;
    }

      /* 100% Image Width on Smaller Screens */
    @media only screen and (max-width: 700px){
      .modal-content {
        width: 100%;
      }
    }
    
    .header{
      margin: 0px;
      padding: 0px;
      border: 0px;
      outline: 0px;
    }
    
    .body{
      margin: 0px;
      padding: 0px;
      border: 0px;
      outline: 0px;
    }
    
    .navbar{
      position: fixed;
      top: 0px;
      left: 0px;
      width: 1500px;
      height: 100px;
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      background-color: #c1e3d8;
    }
    
    .navbar-tool{
      margin-left: 20px;
    }
    
    /* Upload and Download Buttons */
    .button{
      border: 2px solid black;
      border-radius: 5px;
      background-color: white;
      color: black;
      padding: 14px 28px;
      font-size: 16px;
      cursor: pointer;
    }
    
    .download{
      border-color: #2196F3;
      color: dodgerblue;
    }
    
    .download:hover{
      background: #2196F3;
      color: white;
    }
    
    /* Toggle Switch */
    .switch {
      position: relative;
      display: inline-block;
      width: 60px;
      height: 34px;
    }

    .switch input { 
      opacity: 0;
    width: 0;
    height: 0;
    }

    .slider {
      position: absolute;
      cursor: pointer;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: #ccc;
      -webkit-transition: .4s;
      transition: .4s;
    }

    .slider:before {
      position: absolute;
      content: "";
      height: 26px;
      width: 26px;
      left: 4px;
      bottom: 4px;
      background-color: white;
      -webkit-transition: .4s;
      transition: .4s;
    }

    input:checked + .slider {
      background-color: #2196F3;
    }

    input:focus + .slider {
      box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
      -webkit-transform: translateX(26px);
      -ms-transform: translateX(26px);
      transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
      border-radius: 34px;
    }

    .slider.round:before {
      border-radius: 50%;
    }
    
    /* Range Slider */
    section.range-slider {
      position: relative;
      width: 200px;
      height: 35px;
      text-align: center;
    }

    section.range-slider input {
      pointer-events: none;
      position: absolute;
      overflow: hidden;
      left: 0;
      top: 15px;
      width: 200px;
      outline: none;
      height: 18px;
      margin: 0;
      padding: 0;
    }

    section.range-slider input::-webkit-slider-thumb {
      pointer-events: all;
      position: relative;
      z-index: 1;
      outline: 0;
    }

    section.range-slider input::-moz-range-thumb {
      pointer-events: all;
      position: relative;
      z-index: 10;
      -moz-appearance: none;
      width: 9px;
    }

    section.range-slider input::-moz-range-track {
      position: relative;
      z-index: -1;
      background-color: rgba(0, 0, 0, 1);
      border: 0;
    }
    
    section.range-slider input:last-of-type::-moz-range-track {
      -moz-appearance: none;
      background: none transparent;
      border: 0;
    }
    
    section.range-slider input[type=range]::-moz-focus-outer {
      border: 0;
    }
  </style>
</head>

<header>
    
  <!-- contains form to input the files -->
  <nav class="navbar">
    <!-- contains form to input the files -->
    <%= form_for(Place.new) do |f| %>
      <%= f.file_field :images, multiple: true, accept: ".jpg" %>
      <br/>
      <%= f.submit "Submit", id: "sub", hidden: true %>
    <% end %><br/>

	  <button id='download' class="button download">
	    Download
	  </button>
			  
	  <div class = "navbar-tool">
		  <label class="switch">
        <input id="cameraDirection" type="checkbox">
        <span class="slider round"></span>
      </label>
    </div>
    <h3>Direction</h3>
			  
	  <div class = "navbar-tool">
  	  <label class="switch">
        <input id="cameraFOV" type="checkbox">
        <span class="slider round"></span>
      </label>
    </div>
    <h3>FOV</h3>
			  
		<!-- Range Slider -->
	  <div class = "navbar-tool">
  		<section class="range-slider">
        <span class="rangeValues"></span>
        <input id="leftSlider" value="20190708" min="20190708" max="20200115" step="1" type="range">
        <input id="rightSlider" value="20200115" min="20190708" max="20200115" step="1" type="range">
      </section>
    </div>
  </nav>
</header>


<body>
  <script>
    window.imgLocations = <%= @placeAry.to_json.html_safe %>;
    window.L = L;
  </script>
  <div id="map" style="width:100%;height:600px;top:56%"></div>
  <div id="modalContainer"></div>
  <script src="https://npmcdn.com/leaflet-geometryutil"></script>
  <script src="/leaflet-arrowheads.js"></script>
  <script src="/index.js"></script>
</body>

searchandrescue/app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

searchandrescue/app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>